# Anti Combatlog settings
combat:
  tag-duration: 15    # Duration in seconds that players remain in combat after being hit
  ban-duration: 10m   # Duration of the temporary ban (e.g., '10m' for 10 minutes)

# Coins related settings
kill-reward: 10 # Coins rewarded per kill

# Set the spawn region and pvp region. Currently depends on WorldGuard.
spawn-region: "spawn"
pvp-region: "pvp"

# Set options related to respawning and the messages shown while respawning.
respawn:
  countdown: 3
  death-title: "&cYOU DIED!"
  death-subtitle: "&eRespawning in %seconds%..."
  respawn-title: "&aReady to fight."
  respawn-subtitle: ""

# Database options
# Currently supported: mysql and sqlite.
database:
  # Options: 'mysql' or 'sqlite'
  type: 'sqlite'

  mysql:
    host: 'localhost'
    port: '3306'
    database: 'mythica_kitpvp'
    username: 'root'
    password: 'password'

# Custom messages, wow!
messages:
  combat-tagged: "&cYou are now in combat!"
  combat-untagged: "&aYou are no longer in combat!"