name: rKitPvP
version: '${project.version}'
main: me.rhydium.rKitPvP.rKitPvP
api-version: '1.21.4'
authors: [ Rhydium <@rhydium> ]
description: A lightweight, fully customizable KitPvP plugin for Minecraft servers.
depend: [ PlaceholderAPI, WorldEdit, WorldGuard ]
commands:
  kitpvp:
    description: Main KitPvP command with subcommands.
    usage: /kitpvp <build|setspawn|setspawnregion|setpvpregion>
    permission: kitpvp.use
  spawn:
    description: Teleports the player to spawn.
    usage: /spawn
    permission: kitpvp.player.spawn
