name: "\U0001F41E Bug report"
description: Report a problem with rKitPvP
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form as completely as possible.

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      placeholder: "e.g. Paper 1.21.4"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      placeholder: "e.g. 1.0.2"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: "Describe the bug clearly."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: "What should have happened instead?"

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Do this
        2. Then that
        3. See error

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: "You can drag & drop log files here or paste errors."
      render: shell